name: Deploy to Server

on:
  push:
    branches:
      - main  # ou la branche de ton choix

jobs:
  deploy:
    runs-on: debian

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |        
        ssh -i ~/.ssh/id_ed25519_epidictic ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
        "cd ${{ secrets.DEPLOY_PATH }} && git reset --hard && git pull origin main"
